menu:
  -
    nama: Klien
    isi:
      -
        nama: Panglima Delivery
        link: https://panglimadelivery.com
  -
    nama: Media Sosial
    isi:
      -
        nama: Instagram
        link: https://instagram.com/mzaini30
      -
        nama: Github
        link: https://github.com/mzaini30
  -
    nama: Tools
    isi:
      -
        nama: Dokumentasi Bulma
        link: https://github.com/mzaini30/dokumentasi-bulma
      -
        nama: Catatan
        link: https://github.com/mzaini30/catatan
      -
        nama: Codeigniter Twig
        link: https://github.com/mzaini30/codeigniter-twig
      -
        nama: Octocat Downloader
        link: https://github.com/mzaini30/octocat-downloader
      -
        nama: Pecah Satuan
        link: https://github.com/mzaini30/pecah-satuan
      -
        nama: Blade Codeigniter
        link: https://github.com/mzaini30/blade-codeigniter
  -
    nama: Telegram
    isi:
      -
        nama: Aplikasi Android
        link: https://t.me/aplikasiandroid2019