permalink: /:slug-:month:day

paginate: 10
paginate_path: "/halaman-:num"

plugins: 
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

menu:
  -
    nama: Klien
    isi:
      -
        nama: Panglima Delivery
        link: https://panglimadelivery.com
  -
    nama: Media Sosial
    isi:
      -
        nama: Instagram
        link: https://instagram.com/mzaini30
      -
        nama: Github
        link: https://github.com/mzaini30
  -
    nama: Tools
    isi:
      -
        nama: Dokumentasi Bulma
        link: https://github.com/mzaini30/dokumentasi-bulma
      -
        nama: Codeigniter Twig
        link: https://github.com/mzaini30/codeigniter-twig
      -
        nama: Octocat Downloader
        link: https://github.com/mzaini30/octocat-downloader
      -
        nama: Pecah Satuan
        link: https://raw.githubusercontent.com/mzaini30/pecah-satuan/master/pisah%20angka.hta
      -
        nama: Blade Codeigniter
        link: https://github.com/mzaini30/blade-codeigniter
  -
    nama: Form
    isi:
      -
        nama: Sanggar Baca Caraka
        link: https://docs.google.com/forms/d/e/1FAIpQLSei_vNChRWGk_WYKrN_AyVmp0e5pXAZFFSisFqvOCDye6-Avw/viewform
  -
    nama: Blogroll
    isi:
      -
        nama: Wirawan Habibie
        link: https://wirawanhabibie.com/
      -
        nama: Coretan Basayev
        link: https://www.coretanbasayev.com/
      -
        nama: Arsilogi
        link: https://www.arsilogi.id/?m=1
      -
        nama: Jung Jawa
        link: https://www.jungjawa.com/?m=1
  -
    nama: Web Apps
    isi:
      -
        nama: Enter
        link: https://mzaini30.github.io/enter
      -
        nama: Kontur
        link: https://mzaini30.github.io/kontur
      -
        nama: Kontur Reserve
        link: https://mzaini30.github.io/kontur-reserve
      -
        nama: Kontest
        link: https://mzaini30.github.io/kontest
      -
        nama: Markdown
        link: https://mzaini30.github.io/markdown